[tool.black]
line-length = 100
target-version = ["py311", "py313"]
exclude = '''
/(
  \.venv
 | __pycache__
 | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["src", "tests"]
combine_as_imports = true
skip = ["dist", ".venv", "__pycache__"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = [".venv", "__pycache__", "dist"]
per-file-ignores = []

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = false
warn_unreachable = true
disallow_untyped_defs = false
no_implicit_optional = false
exclude = '(\.venv|__pycache__|dist)'
